BEGIN WORK;
DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE account(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  owner BIGINT(20),
  balance FLOAT DEFAULT 0,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
COMMIT;
